version: '3'
services:
  elasticsearch:
     container_name: elasticsearch
     build:
        context: elasticsearch
        args:
           ELK_VERSION: $ELK_VERSION
     volumes:
       - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
       - ./elasticsearch/storage:/usr/share/elasticsearch/data:rw
     ports:
       - "9200:9200"
       - "9300:9300"
     environment:
       - ELASTIC_PASSWORD="changeme"
       - ES_JAVA_OPTS=-Xmx256m -Xms256m
       - discovery.type=single-node
       - bootstrap.memory_lock=true
       - http.cors.allow-origin=*     
     networks:
       - elk
     ulimits:
       memlock:
         soft:  -1
         hard:  -1
  logstash:
     container_name: logstash
     build:
        context: logstash
        args:
          ELK_VERSION: $ELK_VERSION
     volumes:
       - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
       - ./logstash/pipeline:/usr/share/logstash/pipeline
     ports:
       - "5000:5000"
     networks:
       - elk
     depends_on:
       - elasticsearch
  kibana:
     container_name: kibana
     build:
        context: kibana/
        args:
          ELK_VERSION: $ELK_VERSION
     volumes:
       - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
     ports:
       - "5601:5601"
     environment:
       - ELASTICSEARCH_PASSWORD="changeme"
     networks:
       - elk
     depends_on:
       - elasticsearch
  filebeat:
     container_name: filebeat
     build:
        context: filebeat
        args:
          ELK_VERSION: $ELK_VERSION
     volumes:
       - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
       - ./filebeat/log:/usr/share/log
     networks:
       - elk
     depends_on:
       - logstash
networks:
   elk:

